name: bea
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - msys2-conda-epoch=20160418
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - arviz==0.23.0
      - cachetools==6.2.4
      - cloudpickle==3.1.2
      - cons==0.4.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - etuples==0.3.10
      - filelock==3.20.2
      - fonttools==4.61.1
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - kiwisolver==1.4.9
      - logical-unification==0.4.7
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - minikanren==1.0.5
      - multipledispatch==1.0.0
      - numpy==2.2.6
      - packaging==25.0
      - pillow==12.1.0
      - pygments==2.19.2
      - pymc==5.25.1
      - pyparsing==3.3.1
      - pytensor==2.31.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.2.0
      - scipy==1.15.3
      - six==1.17.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - xarray==2025.6.1
      - xarray-einstats==0.8.0
